# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0.xci
# IP: The module: 'axi_spi_top_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0.xci
# IP: The module: 'axi_spi_top_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
