# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xci
# IP: The module: 'PCIEBridge_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xci
# IP: The module: 'PCIEBridge_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
