# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3.xci
# IP: The module: 'PCIEBridge_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/bd_9f1e.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e || ORIG_REF_NAME==bd_9f1e} -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/bd_9f1e_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_1/bd_9f1e_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e_g_inst_0 || ORIG_REF_NAME==bd_9f1e_g_inst_0} -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/bd_9f1e_ila_lib_0_ooc.xdc

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/bd_9f1e_ooc.xdc

# IP: D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3.xci
# IP: The module: 'PCIEBridge_system_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/bd_9f1e.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e || ORIG_REF_NAME==bd_9f1e} -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/bd_9f1e_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_1/bd_9f1e_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9f1e_g_inst_0 || ORIG_REF_NAME==bd_9f1e_g_inst_0} -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_system_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9f1e_ila_lib_0 || ORIG_REF_NAME==bd_9f1e_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/bd_9f1e_ila_lib_0_ooc.xdc

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/bd_9f1e_ooc.xdc
