# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/axi_spi_top_uart_ila_top_0_0.xci
# IP: The module: 'axi_spi_top_uart_ila_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_ila_top_fifo_generator_0_0 || ORIG_REF_NAME==uart_ila_top_fifo_generator_0_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_ila_top_fifo_generator_0_0 || ORIG_REF_NAME==uart_ila_top_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_uart_ila_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/axi_spi_top_uart_ila_top_0_0.xci
# IP: The module: 'axi_spi_top_uart_ila_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_ila_top_fifo_generator_0_0 || ORIG_REF_NAME==uart_ila_top_fifo_generator_0_0} -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_ila_top_fifo_generator_0_0 || ORIG_REF_NAME==uart_ila_top_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado2018_wrk/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_spi_top_uart_ila_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
