# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/PCIeGen2x8If128.xci
# IP: The module: 'PCIeGen2x8If128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen2x8If128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
