# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_spi_top_constrs.xdc

# XDC: D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/constr/KC705_Gen2x8If128.xdc

# Block Designs: bd/PCIEBridge/PCIEBridge.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIEBridge || ORIG_REF_NAME==PCIEBridge} -quiet] -quiet

# IP: bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIEBridge_axis_data_fifo_0_0 || ORIG_REF_NAME==PCIEBridge_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIEBridge_system_ila_0_3 || ORIG_REF_NAME==PCIEBridge_system_ila_0_3} -quiet] -quiet

# IP: bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIEBridge_rst_aclk_250M_2 || ORIG_REF_NAME==PCIEBridge_rst_aclk_250M_2} -quiet] -quiet

# Block Designs: bd/axi_spi_top/axi_spi_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top || ORIG_REF_NAME==axi_spi_top} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_axi_quad_spi_0_0 || ORIG_REF_NAME==axi_spi_top_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/axi_spi_top_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_jtag_axi_0_0 || ORIG_REF_NAME==axi_spi_top_jtag_axi_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_clk_wiz_0_0 || ORIG_REF_NAME==axi_spi_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_axi_periph_0/axi_spi_top_jtag_axi_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_jtag_axi_0_axi_periph_0 || ORIG_REF_NAME==axi_spi_top_jtag_axi_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==axi_spi_top_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_Tgate_0_0/axi_spi_top_Tgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_Tgate_0_0 || ORIG_REF_NAME==axi_spi_top_Tgate_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_Tgate_0_1/axi_spi_top_Tgate_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_Tgate_0_1 || ORIG_REF_NAME==axi_spi_top_Tgate_0_1} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_Tgate_2_0/axi_spi_top_Tgate_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_Tgate_2_0 || ORIG_REF_NAME==axi_spi_top_Tgate_2_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_Tgate_width5_0_0/axi_spi_top_Tgate_width5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_Tgate_width5_0_0 || ORIG_REF_NAME==axi_spi_top_Tgate_width5_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/axi_spi_top_jesd204_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_jesd204_0_0 || ORIG_REF_NAME==axi_spi_top_jesd204_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_xbar_0/axi_spi_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_xbar_0 || ORIG_REF_NAME==axi_spi_top_xbar_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_util_ds_buf_0_0 || ORIG_REF_NAME==axi_spi_top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_inv_0_0/axi_spi_top_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_inv_0_0 || ORIG_REF_NAME==axi_spi_top_inv_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_data_rearrange_0_0/axi_spi_top_data_rearrange_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_data_rearrange_0_0 || ORIG_REF_NAME==axi_spi_top_data_rearrange_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_0/axi_spi_top_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_axi_traffic_gen_0_0 || ORIG_REF_NAME==axi_spi_top_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_init_delay_0_0/axi_spi_top_init_delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_init_delay_0_0 || ORIG_REF_NAME==axi_spi_top_init_delay_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_1/axi_spi_top_axi_traffic_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_axi_traffic_gen_0_1 || ORIG_REF_NAME==axi_spi_top_axi_traffic_gen_0_1} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_2/axi_spi_top_axi_traffic_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_axi_traffic_gen_0_2 || ORIG_REF_NAME==axi_spi_top_axi_traffic_gen_0_2} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_init_delay_0_1/axi_spi_top_init_delay_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_init_delay_0_1 || ORIG_REF_NAME==axi_spi_top_init_delay_0_1} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_data_comb_0_0/axi_spi_top_data_comb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_data_comb_0_0 || ORIG_REF_NAME==axi_spi_top_data_comb_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/axi_spi_top_uart_ila_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_uart_ila_top_0_0 || ORIG_REF_NAME==axi_spi_top_uart_ila_top_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_dds_compiler_0_0 || ORIG_REF_NAME==axi_spi_top_dds_compiler_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_vio_0_0/axi_spi_top_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_vio_0_0 || ORIG_REF_NAME==axi_spi_top_vio_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_err_detector_0_0/axi_spi_top_err_detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_err_detector_0_0 || ORIG_REF_NAME==axi_spi_top_err_detector_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_BridgeToPCIE_0_0/axi_spi_top_BridgeToPCIE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_BridgeToPCIE_0_0 || ORIG_REF_NAME==axi_spi_top_BridgeToPCIE_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_fifo_generator_0_0/axi_spi_top_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_fifo_generator_0_0 || ORIG_REF_NAME==axi_spi_top_fifo_generator_0_0} -quiet] -quiet

# IP: bd/axi_spi_top/ip/axi_spi_top_auto_pc_0/axi_spi_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_spi_top_auto_pc_0 || ORIG_REF_NAME==axi_spi_top_auto_pc_0} -quiet] -quiet

# XDC: bd/PCIEBridge/PCIEBridge_ooc.xdc

# XDC: bd/axi_spi_top/axi_spi_top_ooc.xdc
