# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.cache/wt [current_project]
set_property parent.project_path D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Vivado2018_wrk/UART_ILA_pack/ip_repo [current_project]
set_property ip_output_repo d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_data.coe
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_address.coe
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_1_data.coe
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_1_address.coe
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_2_data.coe
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_2_address.coe
read_verilog {
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/trellis.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/widths.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/functions.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/types.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/xilinx.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/riffa.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tlp.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/ultrascale.vh
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/schedules.vh
}
read_verilog -library xil_defaultlib {
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/hdl/KC705_Gen2x8If128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/async_fifo.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/async_fifo_fwft.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/channel.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/channel_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/channel_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/channel_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/chnl_tester.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/counter.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/cross_domain_signal.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/demux.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/engine_layer.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/ff.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/fifo.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/fifo_packer_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/fifo_packer_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/fifo_packer_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/interrupt.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/interrupt_controller.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/mux.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/offset_flag_to_one_hot.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/offset_to_mask.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/one_hot_mux.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/pipeline.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/ram_1clk_1w_1r.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/ram_2clk_1w_1r.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/recv_credit_flow_ctrl.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/register.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/registers.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/reorder_queue.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/reorder_queue_input.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/reorder_queue_output.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/reset_controller.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/reset_extender.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/riffa.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/riffa_wrapper_kc705.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rotate.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_channel_gate.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_reader.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rx_port_requester_mux.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxc_engine_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxc_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxc_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxr_engine_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxr_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/rxr_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/scsdpram.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/sg_list_reader_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/sg_list_reader_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/sg_list_reader_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/sg_list_requester.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/shiftreg.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/sync_fifo.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/syncff.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/translation_xilinx.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_alignment_pipeline.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_data_fifo.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_data_pipeline.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_data_shift.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_engine.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_engine_selector.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_hdr_fifo.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_multiplexer.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_multiplexer_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_multiplexer_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_multiplexer_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_buffer_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_buffer_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_buffer_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_channel_gate_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_channel_gate_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_channel_gate_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_monitor_128.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_monitor_32.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_monitor_64.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/tx_port_writer.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/txc_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/txc_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/txr_engine_classic.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/riffa_hdl/txr_engine_ultrascale.v
  D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/new/jesd_adc_part.v
}
add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/PCIEBridge.bd
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0/PCIEBridge_axis_data_fifo_0_0.xdc]
set_property used_in_synthesis false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/ip/ip_0/bd_9f1e_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/bd_0/bd_9f1e_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_system_ila_0_3/PCIEBridge_system_ila_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/PCIEBridge_ooc.xdc]

add_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/axi_spi_top.bd
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_quad_spi_0_0/axi_spi_top_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/axi_spi_top_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/constraints/axi_spi_top_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jtag_axi_0_0/axi_spi_top_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_clk_wiz_0_0/axi_spi_top_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_rst_clk_wiz_0_100M_0/axi_spi_top_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/ip_0/axi_spi_top_jesd204_0_0_phy_gt.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/ip_0/axi_spi_top_jesd204_0_0_phy_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/ip_0/synth/axi_spi_top_jesd204_0_0_phy_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/synth/axi_spi_top_jesd204_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_jesd204_0_0/synth/axi_spi_top_jesd204_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_xbar_0/axi_spi_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_util_ds_buf_0_0/axi_spi_top_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_0/axi_spi_top_axi_traffic_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_1/axi_spi_top_axi_traffic_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_axi_traffic_gen_0_2/axi_spi_top_axi_traffic_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_fifo_generator_0_0/uart_ila_top_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_uart_ila_top_0_0/src/uart_ila_top_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_dds_compiler_0_0/axi_spi_top_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_vio_0_0/axi_spi_top_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_vio_0_0/axi_spi_top_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_fifo_generator_0_0/axi_spi_top_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_fifo_generator_0_0/axi_spi_top_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_fifo_generator_0_0/axi_spi_top_fifo_generator_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/ip/axi_spi_top_auto_pc_0/axi_spi_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/axi_spi_top/axi_spi_top_ooc.xdc]

read_ip -quiet D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/PCIeGen2x8If128.xci
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/source/PCIeGen2x8If128-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/ip/synth/PCIeGen2x8If128_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc
set_property used_in_implementation false [get_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc]

read_xdc D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/constr/KC705_Gen2x8If128.xdc
set_property used_in_implementation false [get_files D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/constr/KC705_Gen2x8If128.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top jesd_adc_part -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef jesd_adc_part.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file jesd_adc_part_utilization_synth.rpt -pb jesd_adc_part_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
