# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xci
# IP: The module: 'PCIEBridge_rst_aclk_250M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xci
# IP: The module: 'PCIEBridge_rst_aclk_250M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/sources_1/bd/PCIEBridge/ip/PCIEBridge_rst_aclk_250M_2/PCIEBridge_rst_aclk_250M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIEBridge_rst_aclk_250M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
