set_property SRC_FILE_INFO {cfile:D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/axi_spi_xcross/axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc rfile:../../../axi_spi.srcs/constrs_1/new/axi_spi_top_constrs.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/K7_FMC_PCIE/K7FMC_PCIEDMA_DEMO/xilinx/kc705/KC705_Gen2x8If128/constr/KC705_Gen2x8If128.xdc rfile:../../../../constr/KC705_Gen2x8If128.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10 [get_ports diff_clock_rtl_0_clk_p]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH10 [get_ports diff_clock_rtl_0_clk_n]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T27 [get_ports resetn]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {CS[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {CS[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B23 [get_ports {CS[2]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {CS[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E29 [get_ports {CS[4]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports MISO]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports MOSI]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports sclk]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports GBT_REFCLK_p]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {rxp[0]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {rxp[1]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {rx_sync_p[0]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets dbg_hub_clk_out1]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC20 [get_ports rx_0_0]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports tx_0_0]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets KC705_Gen2x8If128_riffa_inst0/chnl_tx_data_ren]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets KC705_Gen2x8If128_riffa_inst0/chnl_rx]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets KC705_Gen2x8If128_riffa_inst0/rst_out]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets KC705_Gen2x8If128_riffa_inst0/chnl_tx_data_valid]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets KC705_Gen2x8If128_riffa_inst0/chnl_rx_ack]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[44]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[15]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[23]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[70]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[102]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[117]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[120]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[31]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[55]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[17]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[75]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[91]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[96]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[122]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[56]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[5]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[13]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[73]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[94]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[100]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[126]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[37]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[42]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[45]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[53]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[57]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[2]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[26]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[68]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[80]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[104]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[127]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[35]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[49]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[59]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[66]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[3]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[4]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[10]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[86]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[95]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[111]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[118]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[43]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[54]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[18]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[20]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[22]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[90]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[98]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[106]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[113]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[30]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[32]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[47]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[67]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[76]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[81]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[121]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[34]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[78]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[82]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[107]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[125]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[36]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[46]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[61]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[0]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[16]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[25]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[72]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[103]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[105]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[51]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[58]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[65]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[1]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[92]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[110]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[116]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[52]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[8]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[9]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[12]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[77]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[89]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[101]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[112]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[63]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[21]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[69]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[74]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[87]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[93]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[33]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[64]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[19]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[79]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[97]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[114]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[124]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[29]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[40]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[41]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[60]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[14]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[24]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[84]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[88]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[99]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[123]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[38]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[50]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[62]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[6]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[27]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[83]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[108]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[115]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[28]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[39]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[48]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[7]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[11]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[71]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[85]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[109]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_rx_data[119]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[93]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[5]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[79]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[47]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[35]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[21]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[100]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[117]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[118]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[60]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[23]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[27]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[75]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[77]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[83]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[103]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[2]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[32]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[49]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[67]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[56]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[88]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[113]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[121]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[3]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[38]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[46]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[96]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[98]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[108]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[111]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[28]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[48]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[43]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[91]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[7]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[85]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[105]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[126]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[30]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[10]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[0]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[65]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[36]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[73]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[92]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[99]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[122]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[19]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[39]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[17]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[22]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[71]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[76]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[115]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[84]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[25]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[34]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[41]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[80]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[95]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[54]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[112]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[124]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[58]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[6]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[72]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[1]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[81]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[66]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[120]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[125]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[13]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[26]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[51]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[52]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[90]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[97]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[29]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[9]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[20]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[53]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[70]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[55]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[57]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[16]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[42]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[40]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[68]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[69]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[104]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[110]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[114]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[94]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[87]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[109]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[24]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[31]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[33]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[61]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[78]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[63]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[37]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[12]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[62]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[14]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[45]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[101]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[107]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[123]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[15]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[82]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[4]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[59]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[74]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[89]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[102]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[116]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[119]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[127]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[11]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[8]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[18]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[44]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[86]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[50]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[64]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {KC705_Gen2x8If128_riffa_inst0/chnl_tx_data[106]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports PCIE_RESET_N]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y1 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U28 [get_ports {LED[0]}]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports {LED[1]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U25 [get_ports {LED[2]}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U29 [get_ports {LED[3]}]
